import { BlogPost } from './types';

export const blogPosts: BlogPost[] = [
  {
    slug: '10-seo-trends-2026',
    title: '10 SEO Trends That Will Dominate 2026',
    excerpt: 'Stay ahead of the curve with these emerging SEO trends that will shape search engine optimization strategies in 2026 and beyond.',
    author: 'Sarah Mitchell',
    date: '2026-02-10',
    category: 'SEO',
    readTime: '8 min read',
  },
  {
    slug: 'social-media-roi-guide',
    title: 'The Complete Guide to Measuring Social Media ROI',
    excerpt: 'Learn how to track, measure, and prove the return on investment of your social media marketing efforts with our comprehensive guide.',
    author: 'Michael Chen',
    date: '2026-02-05',
    category: 'Social Media',
    readTime: '12 min read',
  },
  {
    slug: 'content-marketing-strategy',
    title: 'Building a Content Marketing Strategy That Converts',
    excerpt: 'Discover the essential elements of a high-performing content marketing strategy that attracts, engages, and converts your target audience.',
    author: 'Emily Rodriguez',
    date: '2026-01-28',
    category: 'Content Marketing',
    readTime: '10 min read',
  },
  {
    slug: 'ppc-optimization-tips',
    title: '15 PPC Optimization Tips to Lower Your Cost Per Click',
    excerpt: 'Reduce your advertising costs and improve campaign performance with these proven PPC optimization techniques.',
    author: 'David Park',
    date: '2026-01-22',
    category: 'PPC',
    readTime: '7 min read',
  },
  {
    slug: 'email-marketing-best-practices',
    title: 'Email Marketing Best Practices for 2026',
    excerpt: 'Maximize your email marketing results with these updated best practices for deliverability, engagement, and conversions.',
    author: 'Jennifer Lee',
    date: '2026-01-15',
    category: 'Email Marketing',
    readTime: '9 min read',
  },
  {
    slug: 'video-marketing-statistics',
    title: 'Video Marketing Statistics Every Marketer Should Know',
    excerpt: 'Explore the latest video marketing statistics and learn why video should be a cornerstone of your digital marketing strategy.',
    author: 'Alex Thompson',
    date: '2026-01-08',
    category: 'Video Marketing',
    readTime: '6 min read',
  },
  {
    slug: 'instagram-algorithm-2026',
    title: 'Understanding the Instagram Algorithm in 2026',
    excerpt: 'Decode the Instagram algorithm and learn how to optimize your content for maximum reach and engagement.',
    author: 'Sarah Mitchell',
    date: '2026-01-02',
    category: 'Social Media',
    readTime: '11 min read',
  },
  {
    slug: 'b2b-lead-generation-tactics',
    title: 'Proven B2B Lead Generation Tactics That Work',
    excerpt: 'Discover effective B2B lead generation strategies that fill your pipeline with qualified prospects ready to buy.',
    author: 'Michael Chen',
    date: '2025-12-18',
    category: 'Lead Generation',
    readTime: '13 min read',
  },
  {
    slug: 'website-conversion-optimization',
    title: 'Website Conversion Optimization: A Step-by-Step Guide',
    excerpt: 'Transform your website into a conversion machine with this comprehensive guide to conversion rate optimization.',
    author: 'Emily Rodriguez',
    date: '2025-12-12',
    category: 'Web Development',
    readTime: '15 min read',
  },
];
