import { CaseStudy } from './types';

export const caseStudies: CaseStudy[] = [
  {
    slug: 'ecommerce-growth-strategy',
    title: 'E-Commerce Growth Strategy',
    client: 'Fashion Retail Brand',
    industry: 'E-Commerce',
    thumbnail: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    heroImage: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    challenge: 'A leading fashion retail brand was struggling with low online visibility and declining sales. Their website traffic had plateaued, and conversion rates were below industry standards.',
    approach: [
      'Conducted comprehensive SEO audit and competitor analysis',
      'Implemented technical SEO improvements and site speed optimization',
      'Developed content marketing strategy with targeted blog posts',
      'Launched multi-channel social media advertising campaigns',
      'Created personalized email marketing automation flows',
    ],
    outcome: {
      description: 'Within 6 months, the client experienced transformative growth across all key metrics, establishing them as a market leader in their segment.',
      metrics: [
        { label: 'Organic Traffic', value: '+285%' },
        { label: 'Conversion Rate', value: '+156%' },
        { label: 'Revenue Growth', value: '+340%' },
        { label: 'ROI', value: '12.5x' },
      ],
    },
    services: ['SEO Optimization', 'Content Marketing', 'Social Media Advertising', 'E-Commerce Development'],
    testimonial: {
      quote: 'AMS Digital transformed our online presence completely. The results exceeded our expectations, and their strategic approach delivered measurable ROI from day one.',
      author: 'Sarah Johnson',
      role: 'Marketing Director',
    },
  },
  {
    slug: 'saas-lead-generation',
    title: 'SaaS Lead Generation Campaign',
    client: 'B2B Software Company',
    industry: 'Technology',
    thumbnail: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    heroImage: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    challenge: 'A B2B SaaS company needed to scale their lead generation efforts while maintaining quality. Their existing campaigns were generating high-cost, low-quality leads.',
    approach: [
      'Developed targeted LinkedIn advertising strategy',
      'Created high-value content assets and lead magnets',
      'Implemented marketing automation and lead scoring',
      'Optimized landing pages for conversion',
      'Launched account-based marketing campaigns',
    ],
    outcome: {
      description: 'The campaign delivered exceptional results, significantly reducing customer acquisition costs while improving lead quality and sales pipeline velocity.',
      metrics: [
        { label: 'Qualified Leads', value: '+420%' },
        { label: 'Cost Per Lead', value: '-65%' },
        { label: 'Sales Pipeline', value: '+$2.4M' },
        { label: 'Close Rate', value: '+89%' },
      ],
    },
    services: ['Lead Generation', 'LinkedIn Marketing', 'Content Marketing', 'Google AdWords'],
    testimonial: {
      quote: 'The quality of leads improved dramatically. Our sales team is now closing deals faster than ever, and our CAC has dropped significantly.',
      author: 'Michael Chen',
      role: 'VP of Sales',
    },
  },
  {
    slug: 'restaurant-brand-transformation',
    title: 'Restaurant Brand Transformation',
    client: 'Multi-Location Restaurant Chain',
    industry: 'Food & Beverage',
    thumbnail: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    heroImage: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    challenge: 'A restaurant chain with 15 locations needed to modernize their brand identity and digital presence to compete with emerging fast-casual competitors.',
    approach: [
      'Complete brand identity redesign including logo and visual system',
      'Developed mobile-first responsive website with online ordering',
      'Created Instagram and Facebook content strategy',
      'Implemented local SEO for all locations',
      'Launched influencer marketing campaigns',
    ],
    outcome: {
      description: 'The brand transformation revitalized the business, attracting a younger demographic and significantly increasing both foot traffic and online orders.',
      metrics: [
        { label: 'Online Orders', value: '+510%' },
        { label: 'Social Engagement', value: '+380%' },
        { label: 'Foot Traffic', value: '+145%' },
        { label: 'Brand Awareness', value: '+265%' },
      ],
    },
    services: ['Logo & Branding Design', 'Website Development', 'Instagram Marketing', 'SEO Optimization'],
    testimonial: {
      quote: 'AMS Digital gave us a fresh, modern identity that resonates with our target audience. Our online ordering has exploded, and we\'re seeing customers we never reached before.',
      author: 'David Martinez',
      role: 'Owner & CEO',
    },
  },
  {
    slug: 'healthcare-reputation-management',
    title: 'Healthcare Reputation Management',
    client: 'Medical Practice Group',
    industry: 'Healthcare',
    thumbnail: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    heroImage: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    challenge: 'A medical practice group was facing negative online reviews and poor search visibility, impacting patient acquisition and trust.',
    approach: [
      'Implemented comprehensive online reputation management strategy',
      'Developed patient review generation system',
      'Created educational content marketing program',
      'Optimized Google My Business listings for all locations',
      'Launched targeted Facebook advertising for specific services',
    ],
    outcome: {
      description: 'The practice group successfully rebuilt their online reputation and became the top-rated provider in their region, leading to significant patient growth.',
      metrics: [
        { label: 'Average Rating', value: '4.8/5' },
        { label: 'Positive Reviews', value: '+450%' },
        { label: 'New Patients', value: '+220%' },
        { label: 'Search Visibility', value: '+310%' },
      ],
    },
    services: ['Online Reputation Management', 'Content Marketing', 'Facebook Marketing', 'SEO Optimization'],
    testimonial: {
      quote: 'Our online reputation was hurting our practice. AMS Digital not only fixed the problem but turned us into the most trusted provider in our area.',
      author: 'Dr. Emily Roberts',
      role: 'Medical Director',
    },
  },
  {
    slug: 'mobile-app-launch',
    title: 'Mobile App Launch Success',
    client: 'Fitness Technology Startup',
    industry: 'Health & Fitness',
    thumbnail: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    heroImage: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    challenge: 'A fitness tech startup needed to launch their mobile app with maximum impact, building user base and generating buzz in a competitive market.',
    approach: [
      'Designed intuitive mobile app UI/UX',
      'Created comprehensive pre-launch marketing strategy',
      'Developed video marketing content for social platforms',
      'Launched influencer partnership program',
      'Implemented app store optimization (ASO)',
    ],
    outcome: {
      description: 'The app launch exceeded all targets, achieving rapid user acquisition and strong engagement metrics that attracted Series A funding.',
      metrics: [
        { label: 'Downloads', value: '150K+' },
        { label: 'Active Users', value: '85K+' },
        { label: 'App Store Rating', value: '4.7/5' },
        { label: 'User Retention', value: '68%' },
      ],
    },
    services: ['Mobile App Design', 'Video Marketing', 'Instagram Marketing', 'Content Marketing'],
    testimonial: {
      quote: 'AMS Digital understood our vision and helped us execute a launch that put us on the map. The user acquisition numbers speak for themselves.',
      author: 'Alex Thompson',
      role: 'Founder & CEO',
    },
  },
  {
    slug: 'real-estate-digital-transformation',
    title: 'Real Estate Digital Transformation',
    client: 'Luxury Real Estate Agency',
    industry: 'Real Estate',
    thumbnail: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    heroImage: '/assets/generated/ams-case-thumb-set.dim_1200x800.png',
    challenge: 'A luxury real estate agency needed to modernize their digital presence and implement systems to compete with tech-forward competitors.',
    approach: [
      'Developed premium website with virtual tour integration',
      'Created high-end video marketing content for properties',
      'Implemented CRM and marketing automation',
      'Launched targeted YouTube advertising campaigns',
      'Developed LinkedIn marketing strategy for agent branding',
    ],
    outcome: {
      description: 'The digital transformation positioned the agency as a market leader, significantly increasing property inquiries and closing high-value deals faster.',
      metrics: [
        { label: 'Property Inquiries', value: '+395%' },
        { label: 'Average Deal Size', value: '+$450K' },
        { label: 'Sales Cycle', value: '-40%' },
        { label: 'Market Share', value: '+28%' },
      ],
    },
    services: ['Website Development', 'Video Marketing', 'YouTube Advertising', 'LinkedIn Marketing'],
    testimonial: {
      quote: 'The new website and marketing strategy have completely transformed how we do business. We\'re closing bigger deals faster than ever before.',
      author: 'Jennifer Williams',
      role: 'Managing Broker',
    },
  },
];
