import { Review } from './types';

export const reviews: Review[] = [
  {
    id: '1',
    client: 'Sarah Johnson',
    company: 'Fashion Retail Brand',
    role: 'Marketing Director',
    rating: 5,
    quote: 'AMS Digital transformed our online presence completely. The results exceeded our expectations, and their strategic approach delivered measurable ROI from day one. Our organic traffic increased by 285% and revenue grew by 340%.',
    outcome: '285% increase in organic traffic, 340% revenue growth',
    project: 'E-Commerce Growth Strategy',
  },
  {
    id: '2',
    client: 'Michael Chen',
    company: 'B2B Software Company',
    role: 'VP of Sales',
    rating: 5,
    quote: 'The quality of leads improved dramatically. Our sales team is now closing deals faster than ever, and our customer acquisition cost has dropped significantly. The LinkedIn campaigns they created were game-changing.',
    outcome: '420% increase in qualified leads, 65% reduction in cost per lead',
    project: 'SaaS Lead Generation Campaign',
  },
  {
    id: '3',
    client: 'David Martinez',
    company: 'Multi-Location Restaurant Chain',
    role: 'Owner & CEO',
    rating: 5,
    quote: 'AMS Digital gave us a fresh, modern identity that resonates with our target audience. Our online ordering has exploded, and we\'re seeing customers we never reached before. The ROI has been incredible.',
    outcome: '510% increase in online orders, 145% increase in foot traffic',
    project: 'Restaurant Brand Transformation',
  },
  {
    id: '4',
    client: 'Dr. Emily Roberts',
    company: 'Medical Practice Group',
    role: 'Medical Director',
    rating: 5,
    quote: 'Our online reputation was hurting our practice. AMS Digital not only fixed the problem but turned us into the most trusted provider in our area. New patient inquiries have more than doubled.',
    outcome: '4.8/5 average rating, 220% increase in new patients',
    project: 'Healthcare Reputation Management',
  },
  {
    id: '5',
    client: 'Alex Thompson',
    company: 'Fitness Technology Startup',
    role: 'Founder & CEO',
    rating: 5,
    quote: 'AMS Digital understood our vision and helped us execute a launch that put us on the map. The user acquisition numbers speak for themselves. We hit 150K downloads in the first three months.',
    outcome: '150K+ downloads, 4.7/5 app store rating, 68% user retention',
    project: 'Mobile App Launch Success',
  },
  {
    id: '6',
    client: 'Jennifer Williams',
    company: 'Luxury Real Estate Agency',
    role: 'Managing Broker',
    rating: 5,
    quote: 'The new website and marketing strategy have completely transformed how we do business. We\'re closing bigger deals faster than ever before. The video marketing has been particularly effective.',
    outcome: '395% increase in property inquiries, $450K higher average deal size',
    project: 'Real Estate Digital Transformation',
  },
  {
    id: '7',
    client: 'Robert Anderson',
    company: 'Manufacturing Company',
    role: 'Marketing Manager',
    rating: 5,
    quote: 'Working with AMS Digital has been a game-changer for our B2B marketing. Their content strategy and LinkedIn campaigns have positioned us as industry leaders and filled our pipeline with qualified opportunities.',
    outcome: 'Generated $3.2M in pipeline value, 180% increase in qualified leads',
    project: 'B2B Content Marketing',
  },
  {
    id: '8',
    client: 'Lisa Park',
    company: 'E-Learning Platform',
    role: 'Head of Growth',
    rating: 5,
    quote: 'The SEO and content marketing work AMS Digital did for us has been phenomenal. We\'ve gone from page 3 to ranking #1 for our most important keywords. Organic traffic is now our #1 customer acquisition channel.',
    outcome: 'Ranking #1 for 45+ keywords, 425% increase in organic traffic',
    project: 'SEO & Content Strategy',
  },
  {
    id: '9',
    client: 'James Wilson',
    company: 'Financial Services Firm',
    role: 'Partner',
    rating: 5,
    quote: 'AMS Digital\'s PPC management has dramatically improved our advertising ROI. They\'ve reduced our cost per lead by 58% while increasing lead volume. Their attention to detail and optimization is impressive.',
    outcome: '58% reduction in cost per lead, 290% increase in lead volume',
    project: 'PPC Campaign Management',
  },
  {
    id: '10',
    client: 'Maria Garcia',
    company: 'Beauty & Wellness Brand',
    role: 'Founder',
    rating: 5,
    quote: 'The Instagram and influencer marketing campaigns AMS Digital created for us have been incredible. Our follower count has grown 10x, and more importantly, we\'re seeing real sales from social media.',
    outcome: '10x follower growth, 520% increase in social media revenue',
    project: 'Social Media Marketing',
  },
];
