import { Service } from './types';

export const services: Service[] = [
  {
    slug: 'logo-and-branding-design',
    title: 'Logo & Branding Design',
    category: 'design',
    icon: 'palette',
    shortDescription: 'Create memorable brand identities that resonate with your target audience and stand out in the market.',
    overview: 'Your brand is more than just a logo—it\'s the complete visual and emotional experience your customers have with your business. Our comprehensive branding services create cohesive, memorable identities that communicate your values and differentiate you from competitors.',
    deliverables: [
      'Custom logo design with multiple concepts',
      'Complete brand style guide',
      'Color palette and typography system',
      'Business card and stationery design',
      'Brand messaging and positioning',
      'Social media visual templates',
    ],
    process: [
      { step: 'Discovery', description: 'Deep dive into your business, values, target audience, and competitive landscape' },
      { step: 'Strategy', description: 'Develop brand positioning and visual direction based on research insights' },
      { step: 'Design', description: 'Create multiple logo concepts and brand identity options' },
      { step: 'Refinement', description: 'Iterate based on feedback to perfect the chosen direction' },
      { step: 'Delivery', description: 'Provide complete brand guidelines and all necessary file formats' },
    ],
    outcomes: [
      'Distinctive brand identity that stands out in your market',
      'Increased brand recognition and recall',
      'Professional, cohesive visual presence across all touchpoints',
      'Clear brand guidelines for consistent future applications',
    ],
    relatedServices: ['graphic-design', 'website-design', 'content-marketing'],
  },
  {
    slug: 'graphic-design',
    title: 'Graphic Design',
    category: 'design',
    icon: 'image',
    shortDescription: 'Professional graphic design services for marketing materials, social media, and digital assets.',
    overview: 'From social media graphics to marketing collateral, our graphic design services ensure every visual touchpoint reinforces your brand and engages your audience. We create designs that not only look great but drive results.',
    deliverables: [
      'Social media graphics and templates',
      'Marketing brochures and flyers',
      'Infographics and data visualizations',
      'Email newsletter templates',
      'Presentation decks',
      'Digital and print advertisements',
    ],
    process: [
      { step: 'Brief', description: 'Understand your goals, audience, and specific design requirements' },
      { step: 'Concept', description: 'Develop initial design concepts aligned with your brand' },
      { step: 'Design', description: 'Create polished designs optimized for their intended use' },
      { step: 'Review', description: 'Gather feedback and make necessary revisions' },
      { step: 'Finalize', description: 'Deliver final files in all required formats' },
    ],
    outcomes: [
      'Eye-catching visuals that capture attention',
      'Consistent brand presentation across all materials',
      'Higher engagement on social media and marketing campaigns',
      'Professional materials that build credibility',
    ],
    relatedServices: ['logo-and-branding-design', 'content-marketing', 'instagram-marketing'],
  },
  {
    slug: 'website-design',
    title: 'Website Design',
    category: 'design',
    icon: 'layout',
    shortDescription: 'Beautiful, user-friendly website designs that convert visitors into customers.',
    overview: 'Your website is often the first impression potential customers have of your business. Our website design services create stunning, intuitive experiences that engage visitors and drive conversions while reflecting your brand perfectly.',
    deliverables: [
      'Custom website design mockups',
      'Mobile-responsive layouts',
      'User experience (UX) optimization',
      'Interactive prototypes',
      'Design system and component library',
      'Accessibility-compliant designs',
    ],
    process: [
      { step: 'Research', description: 'Analyze your audience, competitors, and business goals' },
      { step: 'Wireframing', description: 'Map out site structure and user flows' },
      { step: 'Design', description: 'Create high-fidelity mockups for all key pages' },
      { step: 'Prototype', description: 'Build interactive prototypes for testing' },
      { step: 'Handoff', description: 'Prepare design files for development' },
    ],
    outcomes: [
      'Modern, professional website that builds trust',
      'Improved user experience leading to higher conversions',
      'Mobile-friendly design reaching all audiences',
      'Scalable design system for future growth',
    ],
    relatedServices: ['website-development', 'mobile-app-design', 'logo-and-branding-design'],
  },
  {
    slug: 'mobile-app-design',
    title: 'Mobile App Design',
    category: 'design',
    icon: 'smartphone',
    shortDescription: 'Intuitive mobile app interfaces that users love and engage with daily.',
    overview: 'Mobile apps require specialized design thinking to create experiences that feel native and intuitive. Our mobile app design services focus on usability, performance, and creating interfaces that users want to return to.',
    deliverables: [
      'iOS and Android app designs',
      'User interface (UI) design',
      'User experience (UX) flows',
      'Interactive prototypes',
      'App icon and splash screens',
      'Design specifications for developers',
    ],
    process: [
      { step: 'Discovery', description: 'Understand user needs and app objectives' },
      { step: 'UX Design', description: 'Create user flows and wireframes' },
      { step: 'UI Design', description: 'Design beautiful, intuitive interfaces' },
      { step: 'Prototype', description: 'Build interactive prototypes for testing' },
      { step: 'Testing', description: 'Conduct usability testing and iterate' },
    ],
    outcomes: [
      'Intuitive app interface that users love',
      'Higher user engagement and retention',
      'Reduced development time with clear specifications',
      'App store-ready designs that attract downloads',
    ],
    relatedServices: ['website-design', 'graphic-design', 'video-marketing'],
  },
  {
    slug: 'website-development',
    title: 'Website Development',
    category: 'development',
    icon: 'code',
    shortDescription: 'Fast, secure, and scalable websites built with modern technologies.',
    overview: 'We build websites that are not only beautiful but also fast, secure, and easy to manage. Using modern technologies and best practices, we create web solutions that grow with your business.',
    deliverables: [
      'Custom website development',
      'Content management system (CMS) integration',
      'Mobile-responsive implementation',
      'Performance optimization',
      'Security implementation',
      'Analytics and tracking setup',
    ],
    process: [
      { step: 'Planning', description: 'Define technical requirements and architecture' },
      { step: 'Development', description: 'Build website using modern frameworks and best practices' },
      { step: 'Testing', description: 'Comprehensive testing across devices and browsers' },
      { step: 'Launch', description: 'Deploy to production with monitoring' },
      { step: 'Support', description: 'Ongoing maintenance and updates' },
    ],
    outcomes: [
      'Fast-loading website that ranks well in search',
      'Secure, reliable platform for your business',
      'Easy content management for your team',
      'Scalable solution that grows with you',
    ],
    relatedServices: ['website-design', 'ecommerce-development', 'search-engine-optimization'],
  },
  {
    slug: 'ecommerce-development',
    title: 'E-Commerce Development',
    category: 'development',
    icon: 'shopping-cart',
    shortDescription: 'Powerful online stores that drive sales and provide seamless shopping experiences.',
    overview: 'Our e-commerce development services create online stores that convert browsers into buyers. We build secure, scalable platforms with intuitive shopping experiences and powerful management tools.',
    deliverables: [
      'Custom e-commerce platform',
      'Product catalog management',
      'Shopping cart and checkout',
      'Payment gateway integration',
      'Inventory management system',
      'Order tracking and fulfillment',
    ],
    process: [
      { step: 'Strategy', description: 'Define e-commerce goals and requirements' },
      { step: 'Platform Selection', description: 'Choose the right e-commerce technology' },
      { step: 'Development', description: 'Build custom store with all features' },
      { step: 'Integration', description: 'Connect payment, shipping, and other services' },
      { step: 'Launch', description: 'Deploy and optimize for conversions' },
    ],
    outcomes: [
      'Professional online store that drives sales',
      'Seamless checkout experience reducing cart abandonment',
      'Efficient order management and fulfillment',
      'Scalable platform for business growth',
    ],
    relatedServices: ['website-development', 'search-engine-optimization', 'facebook-advertising'],
  },
  {
    slug: 'search-engine-optimization',
    title: 'Search Engine Optimization (SEO)',
    category: 'marketing',
    icon: 'search',
    shortDescription: 'Increase organic visibility and drive qualified traffic from search engines.',
    overview: 'SEO is the foundation of sustainable online growth. Our comprehensive SEO services improve your search rankings, drive qualified traffic, and establish your authority in your industry.',
    deliverables: [
      'Technical SEO audit and fixes',
      'Keyword research and strategy',
      'On-page optimization',
      'Content optimization',
      'Link building campaigns',
      'Monthly performance reports',
    ],
    process: [
      { step: 'Audit', description: 'Comprehensive analysis of current SEO performance' },
      { step: 'Strategy', description: 'Develop keyword and content strategy' },
      { step: 'Implementation', description: 'Execute technical and on-page optimizations' },
      { step: 'Content', description: 'Create and optimize content for target keywords' },
      { step: 'Monitoring', description: 'Track rankings and adjust strategy' },
    ],
    outcomes: [
      'Higher search engine rankings for target keywords',
      'Increased organic traffic and visibility',
      'More qualified leads from search',
      'Long-term sustainable growth',
    ],
    relatedServices: ['content-marketing', 'website-development', 'lead-generation'],
  },
  {
    slug: 'content-marketing',
    title: 'Content Marketing',
    category: 'marketing',
    icon: 'file-text',
    shortDescription: 'Strategic content that attracts, engages, and converts your target audience.',
    overview: 'Content marketing builds trust, establishes authority, and drives conversions. Our content strategies create valuable resources that attract your ideal customers and guide them through the buyer journey.',
    deliverables: [
      'Content strategy and calendar',
      'Blog posts and articles',
      'Whitepapers and ebooks',
      'Case studies and success stories',
      'Email newsletters',
      'Content performance analytics',
    ],
    process: [
      { step: 'Strategy', description: 'Define content goals and audience personas' },
      { step: 'Planning', description: 'Create content calendar and topics' },
      { step: 'Creation', description: 'Produce high-quality, engaging content' },
      { step: 'Distribution', description: 'Publish and promote across channels' },
      { step: 'Analysis', description: 'Measure performance and optimize' },
    ],
    outcomes: [
      'Increased organic traffic and engagement',
      'Established thought leadership in your industry',
      'More qualified leads from content',
      'Improved SEO performance',
    ],
    relatedServices: ['search-engine-optimization', 'lead-generation', 'medium-marketing'],
  },
  {
    slug: 'lead-generation',
    title: 'Lead Generation',
    category: 'marketing',
    icon: 'users',
    shortDescription: 'Systematic approach to attracting and converting qualified leads for your business.',
    overview: 'Lead generation is about attracting the right prospects and converting them into qualified leads. Our data-driven strategies combine multiple channels to fill your pipeline with high-quality opportunities.',
    deliverables: [
      'Lead generation strategy',
      'Landing page optimization',
      'Lead magnet creation',
      'Marketing automation setup',
      'Lead scoring system',
      'Performance tracking and reporting',
    ],
    process: [
      { step: 'Analysis', description: 'Identify ideal customer profile and channels' },
      { step: 'Strategy', description: 'Develop multi-channel lead generation plan' },
      { step: 'Implementation', description: 'Create campaigns and automation' },
      { step: 'Optimization', description: 'Test and improve conversion rates' },
      { step: 'Nurturing', description: 'Develop lead nurturing sequences' },
    ],
    outcomes: [
      'Consistent flow of qualified leads',
      'Lower cost per lead',
      'Higher lead-to-customer conversion rates',
      'Predictable sales pipeline',
    ],
    relatedServices: ['google-adword', 'linkedin-marketing', 'content-marketing'],
  },
  {
    slug: 'online-reputation-management',
    title: 'Online Reputation Management',
    category: 'marketing',
    icon: 'shield',
    shortDescription: 'Protect and enhance your online reputation across all digital platforms.',
    overview: 'Your online reputation directly impacts customer trust and business growth. Our reputation management services monitor, protect, and enhance how your brand is perceived online.',
    deliverables: [
      'Reputation audit and analysis',
      'Review monitoring and response',
      'Review generation campaigns',
      'Crisis management planning',
      'Positive content creation',
      'Monthly reputation reports',
    ],
    process: [
      { step: 'Audit', description: 'Assess current online reputation' },
      { step: 'Strategy', description: 'Develop reputation management plan' },
      { step: 'Monitoring', description: 'Track mentions and reviews across platforms' },
      { step: 'Response', description: 'Manage and respond to feedback' },
      { step: 'Enhancement', description: 'Generate positive reviews and content' },
    ],
    outcomes: [
      'Improved online ratings and reviews',
      'Increased customer trust and credibility',
      'Better search results for brand name',
      'Protected brand reputation',
    ],
    relatedServices: ['content-marketing', 'search-engine-optimization', 'facebook-marketing'],
  },
  {
    slug: 'quora-marketing',
    title: 'Quora Marketing',
    category: 'marketing',
    icon: 'message-circle',
    shortDescription: 'Establish thought leadership and drive qualified traffic through Quora.',
    overview: 'Quora is a powerful platform for establishing expertise and reaching people actively seeking solutions. Our Quora marketing strategies position you as an authority while driving qualified traffic to your website.',
    deliverables: [
      'Quora profile optimization',
      'Question research and targeting',
      'High-quality answer creation',
      'Quora Ads campaigns',
      'Performance tracking',
      'Monthly activity reports',
    ],
    process: [
      { step: 'Setup', description: 'Optimize profile and identify relevant topics' },
      { step: 'Research', description: 'Find high-value questions to answer' },
      { step: 'Content', description: 'Create detailed, helpful answers' },
      { step: 'Engagement', description: 'Build following and authority' },
      { step: 'Advertising', description: 'Launch targeted Quora Ads campaigns' },
    ],
    outcomes: [
      'Established thought leadership',
      'Qualified referral traffic',
      'Improved brand awareness',
      'Higher domain authority',
    ],
    relatedServices: ['content-marketing', 'medium-marketing', 'linkedin-marketing'],
  },
  {
    slug: 'facebook-marketing',
    title: 'Facebook Marketing',
    category: 'marketing',
    icon: 'facebook',
    shortDescription: 'Build community and engagement on the world\'s largest social network.',
    overview: 'Facebook remains a powerful platform for building community and reaching your target audience. Our Facebook marketing services create engaging content and foster meaningful connections with your customers.',
    deliverables: [
      'Facebook page optimization',
      'Content strategy and calendar',
      'Post creation and scheduling',
      'Community management',
      'Facebook Groups strategy',
      'Performance analytics',
    ],
    process: [
      { step: 'Audit', description: 'Analyze current Facebook presence' },
      { step: 'Strategy', description: 'Develop content and engagement strategy' },
      { step: 'Content', description: 'Create engaging posts and media' },
      { step: 'Engagement', description: 'Respond to comments and messages' },
      { step: 'Analysis', description: 'Track metrics and optimize' },
    ],
    outcomes: [
      'Increased page followers and engagement',
      'Stronger community around your brand',
      'More website traffic from Facebook',
      'Improved brand awareness',
    ],
    relatedServices: ['facebook-advertising', 'instagram-marketing', 'content-marketing'],
  },
  {
    slug: 'instagram-marketing',
    title: 'Instagram Marketing',
    category: 'marketing',
    icon: 'instagram',
    shortDescription: 'Visual storytelling that builds brand awareness and drives engagement.',
    overview: 'Instagram is the premier platform for visual storytelling and brand building. Our Instagram marketing services create stunning content that captures attention and builds a loyal following.',
    deliverables: [
      'Instagram profile optimization',
      'Content strategy and themes',
      'Photo and video content creation',
      'Stories and Reels strategy',
      'Hashtag research and strategy',
      'Engagement and growth tactics',
    ],
    process: [
      { step: 'Audit', description: 'Review current Instagram performance' },
      { step: 'Strategy', description: 'Develop visual content strategy' },
      { step: 'Content', description: 'Create high-quality photos and videos' },
      { step: 'Publishing', description: 'Schedule and post content consistently' },
      { step: 'Growth', description: 'Implement engagement and growth tactics' },
    ],
    outcomes: [
      'Rapid follower growth',
      'Higher engagement rates',
      'Increased brand awareness',
      'More website traffic and conversions',
    ],
    relatedServices: ['instagram-advertising', 'video-marketing', 'graphic-design'],
  },
  {
    slug: 'linkedin-marketing',
    title: 'LinkedIn Marketing',
    category: 'marketing',
    icon: 'linkedin',
    shortDescription: 'B2B marketing and professional networking that generates quality leads.',
    overview: 'LinkedIn is the most effective platform for B2B marketing and professional networking. Our LinkedIn strategies help you connect with decision-makers and establish industry authority.',
    deliverables: [
      'LinkedIn profile/page optimization',
      'Content strategy for professionals',
      'Thought leadership content',
      'Connection and networking strategy',
      'LinkedIn Groups engagement',
      'Performance tracking',
    ],
    process: [
      { step: 'Optimization', description: 'Enhance profile and company page' },
      { step: 'Strategy', description: 'Develop B2B content strategy' },
      { step: 'Content', description: 'Create professional thought leadership content' },
      { step: 'Networking', description: 'Build connections and engage' },
      { step: 'Analysis', description: 'Track leads and engagement' },
    ],
    outcomes: [
      'Increased professional network',
      'More B2B leads and opportunities',
      'Established industry authority',
      'Higher quality business connections',
    ],
    relatedServices: ['linkedin-advertising', 'lead-generation', 'content-marketing'],
  },
  {
    slug: 'twitter-marketing',
    title: 'Twitter Marketing',
    category: 'marketing',
    icon: 'twitter',
    shortDescription: 'Real-time engagement and brand building on Twitter/X.',
    overview: 'Twitter is perfect for real-time engagement, customer service, and building brand personality. Our Twitter marketing services help you join conversations and build a loyal following.',
    deliverables: [
      'Twitter profile optimization',
      'Content strategy and voice',
      'Tweet creation and scheduling',
      'Hashtag strategy',
      'Community engagement',
      'Twitter Spaces strategy',
    ],
    process: [
      { step: 'Setup', description: 'Optimize profile and define voice' },
      { step: 'Strategy', description: 'Develop content and engagement strategy' },
      { step: 'Content', description: 'Create engaging tweets and threads' },
      { step: 'Engagement', description: 'Respond and participate in conversations' },
      { step: 'Growth', description: 'Implement follower growth tactics' },
    ],
    outcomes: [
      'Growing engaged follower base',
      'Increased brand mentions and reach',
      'Better customer relationships',
      'Real-time market insights',
    ],
    relatedServices: ['twitter-advertising', 'content-marketing', 'online-reputation-management'],
  },
  {
    slug: 'video-marketing',
    title: 'Video Marketing',
    category: 'marketing',
    icon: 'video',
    shortDescription: 'Compelling video content that captures attention and drives action.',
    overview: 'Video is the most engaging content format across all platforms. Our video marketing services create compelling visual stories that capture attention, explain complex ideas, and drive conversions.',
    deliverables: [
      'Video marketing strategy',
      'Script writing and storyboarding',
      'Video production and editing',
      'Platform optimization',
      'Video SEO',
      'Performance analytics',
    ],
    process: [
      { step: 'Strategy', description: 'Define video goals and concepts' },
      { step: 'Pre-production', description: 'Script, storyboard, and plan shoots' },
      { step: 'Production', description: 'Film high-quality video content' },
      { step: 'Post-production', description: 'Edit and optimize videos' },
      { step: 'Distribution', description: 'Publish and promote across channels' },
    ],
    outcomes: [
      'Higher engagement across all platforms',
      'Improved message retention',
      'Increased conversions',
      'Stronger emotional connection with audience',
    ],
    relatedServices: ['youtube-advertising', 'instagram-marketing', 'content-marketing'],
  },
  {
    slug: 'medium-marketing',
    title: 'Medium Marketing',
    category: 'marketing',
    icon: 'book-open',
    shortDescription: 'Thought leadership and content distribution on Medium\'s engaged platform.',
    overview: 'Medium provides access to a highly engaged audience of readers seeking quality content. Our Medium marketing services help you establish thought leadership and reach new audiences.',
    deliverables: [
      'Medium profile optimization',
      'Content strategy for Medium',
      'Article writing and publishing',
      'Publication submissions',
      'Engagement tactics',
      'Performance tracking',
    ],
    process: [
      { step: 'Setup', description: 'Optimize profile and identify publications' },
      { step: 'Strategy', description: 'Develop content topics and themes' },
      { step: 'Writing', description: 'Create high-quality articles' },
      { step: 'Publishing', description: 'Publish and submit to publications' },
      { step: 'Promotion', description: 'Promote articles across channels' },
    ],
    outcomes: [
      'Expanded content reach',
      'Established thought leadership',
      'Quality backlinks for SEO',
      'New audience discovery',
    ],
    relatedServices: ['content-marketing', 'quora-marketing', 'linkedin-marketing'],
  },
  {
    slug: 'google-adword',
    title: 'Google Ads (AdWords)',
    category: 'advertising',
    icon: 'target',
    shortDescription: 'Targeted search advertising that captures high-intent customers.',
    overview: 'Google Ads puts your business in front of people actively searching for your products or services. Our Google Ads management delivers qualified traffic and measurable ROI.',
    deliverables: [
      'Google Ads account setup',
      'Keyword research and strategy',
      'Ad copy creation and testing',
      'Landing page optimization',
      'Bid management and optimization',
      'Detailed performance reports',
    ],
    process: [
      { step: 'Research', description: 'Keyword and competitor research' },
      { step: 'Strategy', description: 'Develop campaign structure and targeting' },
      { step: 'Setup', description: 'Create campaigns, ad groups, and ads' },
      { step: 'Launch', description: 'Launch campaigns with monitoring' },
      { step: 'Optimization', description: 'Continuously test and improve performance' },
    ],
    outcomes: [
      'Immediate qualified traffic',
      'Lower cost per acquisition',
      'Higher conversion rates',
      'Measurable ROI',
    ],
    relatedServices: ['display-marketing', 'pay-per-click', 'lead-generation'],
  },
  {
    slug: 'display-marketing',
    title: 'Display Marketing',
    category: 'advertising',
    icon: 'monitor',
    shortDescription: 'Visual advertising across the web to build awareness and drive conversions.',
    overview: 'Display advertising builds brand awareness and reaches your audience across millions of websites. Our display marketing campaigns combine compelling creative with precise targeting.',
    deliverables: [
      'Display ad strategy',
      'Banner ad design (all sizes)',
      'Audience targeting setup',
      'Remarketing campaigns',
      'A/B testing',
      'Performance optimization',
    ],
    process: [
      { step: 'Strategy', description: 'Define goals and target audiences' },
      { step: 'Creative', description: 'Design compelling display ads' },
      { step: 'Targeting', description: 'Set up audience and placement targeting' },
      { step: 'Launch', description: 'Launch campaigns across networks' },
      { step: 'Optimization', description: 'Test and optimize for performance' },
    ],
    outcomes: [
      'Increased brand awareness',
      'Higher website traffic',
      'Effective remarketing to past visitors',
      'Improved conversion rates',
    ],
    relatedServices: ['google-adword', 'facebook-advertising', 'graphic-design'],
  },
  {
    slug: 'facebook-advertising',
    title: 'Facebook Advertising',
    category: 'advertising',
    icon: 'facebook',
    shortDescription: 'Precision-targeted ads on Facebook and Instagram that drive results.',
    overview: 'Facebook Ads offer unparalleled targeting capabilities to reach your ideal customers. Our Facebook advertising services create campaigns that drive awareness, engagement, and conversions.',
    deliverables: [
      'Facebook Ads strategy',
      'Audience research and targeting',
      'Ad creative design',
      'Campaign setup and management',
      'A/B testing',
      'Performance reporting',
    ],
    process: [
      { step: 'Strategy', description: 'Define objectives and target audiences' },
      { step: 'Creative', description: 'Design ads and write compelling copy' },
      { step: 'Targeting', description: 'Set up detailed audience targeting' },
      { step: 'Launch', description: 'Launch campaigns with proper tracking' },
      { step: 'Optimization', description: 'Continuously improve performance' },
    ],
    outcomes: [
      'Precise audience targeting',
      'Lower cost per result',
      'Higher engagement and conversions',
      'Scalable campaign performance',
    ],
    relatedServices: ['instagram-advertising', 'facebook-marketing', 'video-marketing'],
  },
  {
    slug: 'instagram-advertising',
    title: 'Instagram Advertising',
    category: 'advertising',
    icon: 'instagram',
    shortDescription: 'Visual advertising on Instagram that captures attention and drives action.',
    overview: 'Instagram Ads leverage the platform\'s visual nature to create thumb-stopping advertisements. Our Instagram advertising services create campaigns that blend seamlessly into feeds while driving results.',
    deliverables: [
      'Instagram Ads strategy',
      'Visual ad creative',
      'Stories and Reels ads',
      'Audience targeting',
      'Campaign management',
      'Performance analytics',
    ],
    process: [
      { step: 'Strategy', description: 'Define campaign goals and audiences' },
      { step: 'Creative', description: 'Create stunning visual ads' },
      { step: 'Setup', description: 'Configure campaigns and targeting' },
      { step: 'Launch', description: 'Launch with proper tracking' },
      { step: 'Optimization', description: 'Test and improve performance' },
    ],
    outcomes: [
      'High engagement rates',
      'Increased brand awareness',
      'More website traffic and sales',
      'Growing Instagram following',
    ],
    relatedServices: ['facebook-advertising', 'instagram-marketing', 'video-marketing'],
  },
  {
    slug: 'linkedin-advertising',
    title: 'LinkedIn Advertising',
    category: 'advertising',
    icon: 'linkedin',
    shortDescription: 'B2B advertising that reaches decision-makers and generates quality leads.',
    overview: 'LinkedIn Ads are the most effective way to reach B2B decision-makers. Our LinkedIn advertising services create campaigns that generate high-quality leads and drive business growth.',
    deliverables: [
      'LinkedIn Ads strategy',
      'Ad creative and copy',
      'Audience targeting setup',
      'Lead gen form creation',
      'Campaign management',
      'Lead quality analysis',
    ],
    process: [
      { step: 'Strategy', description: 'Define B2B goals and target personas' },
      { step: 'Targeting', description: 'Set up precise professional targeting' },
      { step: 'Creative', description: 'Create professional ad content' },
      { step: 'Launch', description: 'Launch campaigns with lead tracking' },
      { step: 'Optimization', description: 'Optimize for lead quality and cost' },
    ],
    outcomes: [
      'High-quality B2B leads',
      'Reach decision-makers directly',
      'Lower cost per qualified lead',
      'Faster sales cycles',
    ],
    relatedServices: ['linkedin-marketing', 'lead-generation', 'content-marketing'],
  },
  {
    slug: 'twitter-advertising',
    title: 'Twitter Advertising',
    category: 'advertising',
    icon: 'twitter',
    shortDescription: 'Real-time advertising on Twitter/X that drives engagement and conversions.',
    overview: 'Twitter Ads help you reach engaged audiences in real-time. Our Twitter advertising services create campaigns that drive awareness, engagement, and website traffic.',
    deliverables: [
      'Twitter Ads strategy',
      'Ad creative and copy',
      'Audience targeting',
      'Campaign setup',
      'Performance optimization',
      'Analytics and reporting',
    ],
    process: [
      { step: 'Strategy', description: 'Define campaign objectives' },
      { step: 'Creative', description: 'Create engaging ad content' },
      { step: 'Targeting', description: 'Set up audience and interest targeting' },
      { step: 'Launch', description: 'Launch campaigns with tracking' },
      { step: 'Optimization', description: 'Improve performance continuously' },
    ],
    outcomes: [
      'Increased brand awareness',
      'Higher engagement rates',
      'More website traffic',
      'Growing follower base',
    ],
    relatedServices: ['twitter-marketing', 'video-marketing', 'content-marketing'],
  },
  {
    slug: 'youtube-advertising',
    title: 'YouTube Advertising',
    category: 'advertising',
    icon: 'youtube',
    shortDescription: 'Video advertising on YouTube that reaches billions of viewers.',
    overview: 'YouTube is the second-largest search engine and offers massive reach for video advertising. Our YouTube advertising services create campaigns that capture attention and drive action.',
    deliverables: [
      'YouTube Ads strategy',
      'Video ad production',
      'Audience targeting',
      'Campaign setup and management',
      'Performance optimization',
      'Detailed analytics',
    ],
    process: [
      { step: 'Strategy', description: 'Define video ad objectives' },
      { step: 'Production', description: 'Create compelling video ads' },
      { step: 'Targeting', description: 'Set up audience and placement targeting' },
      { step: 'Launch', description: 'Launch campaigns across YouTube' },
      { step: 'Optimization', description: 'Optimize for views and conversions' },
    ],
    outcomes: [
      'Massive reach and impressions',
      'High engagement with video content',
      'Increased brand awareness',
      'More website traffic and conversions',
    ],
    relatedServices: ['video-marketing', 'google-adword', 'display-marketing'],
  },
  {
    slug: 'pay-per-click',
    title: 'Pay-Per-Click (PPC)',
    category: 'advertising',
    icon: 'mouse-pointer',
    shortDescription: 'Comprehensive PPC management across all major advertising platforms.',
    overview: 'PPC advertising delivers immediate results and measurable ROI. Our comprehensive PPC management services optimize campaigns across all major platforms to maximize your advertising investment.',
    deliverables: [
      'Multi-platform PPC strategy',
      'Campaign setup and management',
      'Keyword and audience research',
      'Ad creative and copy',
      'Landing page optimization',
      'Comprehensive reporting',
    ],
    process: [
      { step: 'Audit', description: 'Analyze current PPC performance' },
      { step: 'Strategy', description: 'Develop comprehensive PPC strategy' },
      { step: 'Implementation', description: 'Set up campaigns across platforms' },
      { step: 'Management', description: 'Daily monitoring and optimization' },
      { step: 'Reporting', description: 'Provide detailed performance insights' },
    ],
    outcomes: [
      'Lower cost per acquisition',
      'Higher conversion rates',
      'Better ROI on ad spend',
      'Scalable advertising performance',
    ],
    relatedServices: ['google-adword', 'facebook-advertising', 'linkedin-advertising'],
  },
];
